<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class BloodDonorUsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('blood_donor_users')->insert([
            [
                'username' => 'user10',
                'full_name' => 'Olivia Taylor',
                'gender' => 'Female',
                'blood_type' => 'A+',
                'address' => 'Address 10',
                'phone_number' => '2223334444',
                'birthdate' => '1984-12-08',
                'email' => 'user10@example.com',
                'password' => Hash::make('password10'),
                'status' => 'Active',
            ],
            [
                'username' => 'user11',
                'full_name' => 'Chris Evans',
                'gender' => 'Male',
                'blood_type' => 'O+',
                'address' => 'Address 11',
                'phone_number' => '5554443333',
                'birthdate' => '1997-06-28',
                'email' => 'user11@example.com',
                'password' => Hash::make('password11'),
                'status' => 'Active',

            ],
            [   'username' => 'user12',
                'full_name' => 'Mia Johnson',
                'gender' => 'Female',
                'blood_type' => 'B+',
                'address' => 'Address 12',
                'phone_number' => '1112223333',
                'birthdate' => '1986-10-15',
                'email' => 'user12@example.com',
                'password' => Hash::make('password12'),
                'status' => 'Active',
            ],
            [   'username' => 'user13',
                'full_name' => 'Alex Turner',
                'gender' => 'Male',
                'blood_type' => 'A-',
                'address' => 'Address 13',
                'phone_number' => '9998887777',
                'birthdate' => '1994-03-20',
                'email' => 'user13@example.com',
                'password' => Hash::make('password13'),
                'status' => 'Active',
            ],
            [   'username' => 'user14',
                'full_name' => 'Emma Stone',
                'gender' => 'Female',
                'blood_type' => 'AB+',
                'address' => 'Address 14',
                'phone_number' => '7776665555',
                'birthdate' => '1983-07-30',
                'email' => 'user14@example.com',
                'password' => Hash::make('password14'),
                'status' => 'Active',
            ],
            [   'username' => 'user15',
                'full_name' => 'Matthew Harris',
                'gender' => 'Male',
                'blood_type' => 'B-',
                'address' => 'Address 15',
                'phone_number' => '3332221111',
                'birthdate' => '1999-01-10',
                'email' => 'user15@example.com',
                'password' => Hash::make('password15'),
                'status' => 'Active',
            ],
            [   'username' => 'user16',
                'full_name' => 'Sophia Walker',
                'gender' => 'Female',
                'blood_type' => 'O-',
                'address' => 'Address 16',
                'phone_number' => '8889990000',
                'birthdate' => '1988-05-25',
                'email' => 'user16@example.com',
                'password' => Hash::make('password16'),
                'status' => 'Active',
            ],
            [   'username' => 'user17',
                'full_name' => 'Ryan Martinez',
                'gender' => 'Male',
                'blood_type' => 'A+',
                'address' => 'Address 17',
                'phone_number' => '2223334444',
                'birthdate' => '1992-02-18',
                'email' => 'user17@example.com',
                'password' => Hash::make('password17'),
                'status' => 'Active',
            ],
            [   'username' => 'user18',
                'full_name' => 'Isabella Turner',
                'gender' => 'Female',
                'blood_type' => 'AB-',
                'address' => 'Address 18',
                'phone_number' => '4445556666',
                'birthdate' => '1989-08-05',
                'email' => 'user18@example.com',
                'password' => Hash::make('password18'),
                'status' => 'Active',
            ],
            [   'username' => 'user19',
                'full_name' => 'Nathan Adams',
                'gender' => 'Male',
                'blood_type' => 'B+',
                'address' => 'Address 19',
                'phone_number' => '9998887777',
                'birthdate' => '1995-04-12',
                'email' => 'user19@example.com',
                'password' => Hash::make('password19'),
                'status' => 'Active',
            ],
            [
                'username' => 'user1',
                'full_name' => 'John Doe',
                'gender' => 'Male',
                'blood_type' => 'A+',
                'address' => 'Address 1',
                'phone_number' => '1234567890',
                'birthdate' => '1990-01-01',
                'email' => 'user1@example.com',
                'password' => Hash::make('password1'),
                'status' => 'Active',
            ],
            [
                'username' => 'user20',
                'full_name' => 'Lily Wilson',
                'gender' => 'Female',
                'blood_type' => 'A+',
                'address' => 'Address 20',
                'phone_number' => '5554443333',
                'birthdate' => '1987-12-08',
                'email' => 'user20@example.com',
                'password' => Hash::make('password20'),
                'status' => 'Active',
            ],
            [
                'username' => 'user2',
                'full_name' => 'Jane Doe',
                'gender' => 'Female',
                'blood_type' => 'B-',
                'address' => 'Address 2',
                'phone_number' => '9876543210',
                'birthdate' => '1985-03-15',
                'email' => 'user2@example.com',
                'password' => Hash::make('password2'),
                'status' => 'Active',
            ],
            [
                'username' => 'user3',
                'full_name' => 'Bob Smith',
                'gender' => 'Male',
                'blood_type' => 'O+',
                'address' => 'Address 3',
                'phone_number' => '5551112233',
                'birthdate' => '1995-07-20',
                'email' => 'user3@example.com',
                'password' => Hash::make('password3'),
                'status' => 'Active',
            ],
            [
                'username' => 'user4',
                'full_name' => 'Alice Johnson',
                'gender' => 'Female',
                'blood_type' => 'AB+',
                'address' => 'Address 4',
                'phone_number' => '9998887777',
                'birthdate' => '1982-11-30',
                'email' => 'user4@example.com',
                'password' => Hash::make('password4'),
                'status' => 'Active',
            ],
            [
                'username' => 'user5',
                'full_name' => 'Michael Brown',
                'gender' => 'Male',
                'blood_type' => 'B+',
                'address' => 'Address 5',
                'phone_number' => '3332221111',
                'birthdate' => '1998-05-10',
                'email' => 'user5@example.com',
                'password' => Hash::make('password5'),
                'status' => 'Active',
            ],
            [
                'username' => 'user6',
                'full_name' => 'Sara Miller',
                'gender' => 'Female',
                'blood_type' => 'O-',
                'address' => 'Address 6',
                'phone_number' => '7776665555',
                'birthdate' => '1989-09-25',
                'email' => 'user6@example.com',
                'password' => Hash::make('password6'),
                'status' => 'Active',
            ],
            [
                'username' => 'user7',
                'full_name' => 'Tom Wilson',
                'gender' => 'Male',
                'blood_type' => 'A-',
                'address' => 'Address 7',
                'phone_number' => '1112223333',
                'birthdate' => '1993-02-18',
                'email' => 'user7@example.com',
                'password' => Hash::make('password7'),
                'status' => 'Active',
            ],
            [
                'username' => 'user8',
                'full_name' => 'Emily Davis',
                'gender' => 'Female',
                'blood_type' => 'AB-',
                'address' => 'Address 8',
                'phone_number' => '4445556666',
                'birthdate' => '1987-08-05',
                'email' => 'user8@example.com',
                'password' => Hash::make('password8'),
                'status' => 'Active',
            ],
            [
                'username' => 'user9',
                'full_name' => 'Daniel White',
                'gender' => 'Male',
                'blood_type' => 'B+',
                'address' => 'Address 9',
                'phone_number' => '8889990000',
                'birthdate' => '1996-04-12',
                'email' => 'user9@example.com',
                'password' => Hash::make('password9'),
                'status' => 'Active',
            ],
        ]);
    }
}
